#### **Fake News Detector**

In [1]:
import requests
import os
from dotenv import load_dotenv
import pandas as pd
import time

status = load_dotenv("../../secrets.env")
if status:
    print("Success: secrets.env loaded!")
else:
    print("Fail: Could not find or read secrets.env.")

Success: secrets.env loaded!

In [2]:
token = os.getenv("HUGGING_FACE_token")
headers = {"Authorization": f"Bearer {token}"}

In [3]:
#url = "https://api-inference.huggingface.co/models/your-username/fake-news-bert"
#url = "https://router.huggingface.co/hf-inference/models/your-username/fake-news-bert"
url = "https://router.huggingface.co/hf-inference/models/hamzab/roberta-fake-news-classification"
#url = "https://router.huggingface.co/hf-inference/models/jy46604790/Fake-News-Bert-Detect"
#url = "https://router.huggingface.co/hf-inference/models/mrm8488/bert-tiny-finetuned-fake-news-detection"

payload = {"inputs": " Top Trump Surrogate BRUTALLY Stabs Him In The Back: â€˜Heâ€™s Patheticâ€™ (VIDEO) It s looking as though Republican presidential candidate Donald Trump is losing support even from within his own ranks. You know things are getting bad when even your top surrogates start turning against you, which is exactly what just happened on Fox News when Newt Gingrich called Trump  pathetic. Gingrich knows that Trump needs to keep his focus on Hillary Clinton if he even remotely wants to have a chance at defeating her. However, Trump has hurt feelings because many Republicans don t support his sexual assault against women have turned against him, including House Speaker Paul Ryan (R-WI). So, that has made Trump lash out as his own party.Gingrich said on Fox News: Look, first of all, let me just say about Trump, who I admire and I ve tried to help as much as I can. There s a big Trump and a little Trump. The little Trump is frankly pathetic. I mean, he s mad over not getting a phone call? Trump s referring to the fact that Paul Ryan didn t call to congratulate him after the debate. Probably because he didn t win despite what Trump s ego tells him.Gingrich also added: Donald Trump has one opponent. Her name is Hillary Clinton. Her name is not Paul Ryan. It s not anybody else. Trump doesn t seem to realize that the person he should be mad at is himself because he truly is his own worst enemy. This will ultimately lead to his defeat and he will have no one to blame but himself.Watch here via Politico:Featured Photo by Joe Raedle/Getty Images"}

response = requests.post(url, headers=headers, json=payload)

# Check if the request was successful
if response.status_code == 200:
    prediction = response.json()
    print(f"Prediction: {prediction}")
else:
    print(f"Error {response.status_code}: {response.text}")

Prediction: [[{'label': 'FAKE', 'score': 0.9999797344207764}, {'label': 'TRUE', 'score': 2.029385905188974e-05}]]

In [4]:
#df = pd.read_csv("./data2/cleaned_file_totally.csv")
df = pd.read_csv("./data4/WELFake_clean.csv")

In [5]:
df

                                                    Text label
0      LAW ENFORCEMENT ON HIGH ALERT Following Threat...  Fake
1         Did they post their votes for Hillary already?  Fake
2      UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...  Fake
3      Bobby Jindal, raised Hindu, uses story of Chri...  Real
4      SATAN 2: Russia unvelis an image of its terrif...  Fake
...                                                  ...   ...
72129  Russians steal research on Trump in hack of U....  Real
72130  WATCH: Giuliani Demands That Democrats Apologi...  Fake
72131  Migrants Refuse To Leave Train At Refugee Camp...  Real
72132  Trump tussle gives unpopular Mexican leader mu...  Real
72133  Goldman Sachs Endorses Hillary Clinton For Pre...  Fake

[72134 rows x 2 columns]

In [6]:
df['length'] = df.iloc[:, 0].astype(str).str.len()

In [7]:
df['truncated_text'] = df['Text'].str[:2200]
df.head(1)

,Text,label,length,truncated_text
0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,Fake,5180,LAW ENFORCEMENT ON HIGH ALERT Following Threat...

In [8]:
# result: [[{'label': 'FAKE', 'score': 0.9999797344207764}, {'label': 'TRUE', 'score': 2.029385905188974e-05}]]
def classify(text, retries=15, wait=20):
    payload = {"inputs": str(text)}
    for attempt in range(retries):
        try:
            response = requests.post(url, headers=headers, json=payload, timeout=30)
            if response.status_code == 200:
                results = response.json()[0]
                best   = max(results, key=lambda x: x["score"])
                label  = best["label"].upper()
                pred_label = "REAL" if label == "TRUE" else label
                pred_prob = best["score"]
                return pred_label, pred_prob
            elif response.status_code == 503:
                print(f"  Model loading, waiting {wait}s... (attempt {attempt+1})")
                time.sleep(wait)
            elif response.status_code == 400:
                # Bad request — no point retrying with same text, skip immediately
                print(f"  [Attempt {attempt+1}/{retries}] HTTP 400 Bad Request: {response.text[:120]}")
                print(f"  Truncating further and retrying...")
                text = text[:2200-(250*(attempt+1))]  # shrink text each retry
                payload = {"inputs": text}
                time.sleep(2)
            else:
                print(f"  HTTP {response.status_code}: {response.text[:120]}")
                return "ERROR", 0.0
        except Exception as e:
            print(response.status_code)
            print(f"  [Attempt {attempt+1}/{retries}] Exception: {e} — retrying in {wait}s...")
            time.sleep(wait)
    return "ERROR"

In [9]:
predictions = []
probs = []

for i, row in df.iterrows():
    text  = row["truncated_text"]
    label_p, prob_p = classify(text)
    predictions.append(label_p)
    probs.append(prob_p)
    print(f"[{i+1}/{len(df)}] → {row['label']} > {label_p} {label_p} {prob_p * 100:.3f}%| {str(text)[:80]}")
    time.sleep(0.5)  # polite API usage

df["Prediction"] = predictions
df.head(10)

  [Attempt 1/15] HTTP 400 Bad Request: {"error":"The expanded size of the tensor (558) must match the existing size (514) at non-singleton dimension 1.  Target
  Truncating further and retrying...
[1/72134] → Fake > FAKE FAKE 99.998%| LAW ENFORCEMENT ON HIGH ALERT Following Threats Against Cops And Whites On 9-11B
[2/72134] → Fake > FAKE FAKE 99.948%| Did they post their votes for Hillary already?
[3/72134] → Fake > FAKE FAKE 99.998%| UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MOST CHARLOTTE RIOTERS WERE “PEACEFU
[4/72134] → Real > REAL REAL 99.996%| Bobby Jindal, raised Hindu, uses story of Christian conversion to woo evangelica
[5/72134] → Fake > REAL REAL 99.985%| SATAN 2: Russia unvelis an image of its terrifying new ‘SUPERNUKE’ – Western wor
[6/72134] → Fake > FAKE FAKE 99.994%| About Time! Christian Group Sues Amazon and SPLC for Designation as Hate Group A
[7/72134] → Fake > FAKE FAKE 99.998%| DR BEN CARSON TARGETED BY THE IRS: “I never had an audit until I spoke at the Na
[8/72134] → Fake > FAKE FAKE 99.998%| HOUSE INTEL CHAIR On Trump-Russia Fake Story: “No evidence of anything” [Video]
[9/72134] → Fake > FAKE FAKE 99.998%| Sports Bar Owner Bans NFL Games…Will Show Only ‘True American’ Sports: ‘I’d like
[10/72134] → Fake > FAKE FAKE 99.993%| Latest Pipeline Leak Underscores Dangers Of Dakota Access Pipeline In this Sept.
  [Attempt 1/15] HTTP 400 Bad Request: {"error":"The expanded size of the tensor (570) must match the existing size (514) at non-singleton dimension 1.  Target
  Truncating further and retrying...
[11/72134] → Fake > FAKE FAKE 99.998%| GOP Senator Just Smacked Down The Most Punchable Alt-Right Nazi On The Internet
[12/72134] → Real > REAL REAL 99.997%| May Brexit offer would hurt, cost EU citizens - EU parliament British Prime Mini
[13/72134] → Real > REAL REAL 99.997%| Schumer calls on Trump to appoint official to oversee Puerto Rico relief Charles
[14/72134] → Fake > FAKE FAKE 99.998%| WATCH: HILARIOUS AD Calls Into Question Health Of Aging Clinton Crime Family Bos
[15/72134] → Real > FAKE FAKE 99.996%| No Change Expected for ESPN Political Agenda Despite Huge Subscriber Decline - B
[16/72134] → Real > REAL REAL 99.996%| Billionaire Odebrecht in Brazil scandal released to house arrest Billionaire Mar
[17/72134] → Fake > FAKE FAKE 99.998%| BRITISH WOMAN LOSES VIRGINITY To Asylum Seeking Rapist On Her Way To Church Euro
[18/72134] → Real > REAL REAL 99.997%| U.N. seeks humanitarian pause in Sanaa where streets "battlegrounds" The United
[19/72134] → Fake > FAKE FAKE 99.998%| MAJOR LIBERAL RAG RELUCTANTLY PUBLISHES Article On President Trump’s Outstanding
[20/72134] → Real > REAL REAL 99.997%| Second judge says Clinton email setup may have been in 'bad faith' A second fede
[21/72134] → Fake > REAL REAL 99.974%| America gives Grand Piano to horse Wednesday 9 November 2016 by Lucas Wilde Amer
  [Attempt 1/15] HTTP 400 Bad Request: {"error":"The expanded size of the tensor (520) must match the existing size (514) at non-singleton dimension 1.  Target
  Truncating further and retrying...
[22/72134] → Fake > FAKE FAKE 99.925%| Hillary’s crime family: End of days for the U.S.A Hillary’s crime family: End of
[23/72134] → Fake > FAKE FAKE 99.998%| Sean Spicer Baffles Reporters, Claims Trump Isn’t Responsible For Hiring Flynn (
[24/72134] → Fake > FAKE FAKE 99.998%| UNHOLY ALLIANCE: Hillary Clinton’s Saudi Sponsors Support Terrorism, Islamist Ex
[25/72134] → Fake > FAKE FAKE 99.998%| Even Trump’s Best Friend Joe Scarborough Can’t Handle His ‘Disqualifying’ KKK Su
[26/72134] → Fake > FAKE FAKE 99.998%| BOOM! Danish Government Considers Seizing Migrant’s Valuables To Pay For Benefit
[27/72134] → Real > FAKE FAKE 99.992%| Supreme Court Won’t Hear Appeal From Texas on Voter ID Case - The New York Times
[28/72134] → Real > REAL REAL 99.996%| Islamic State driven out of last stronghold in northern Iraq Iraqi forces announ
[29/72134] → Real > FAKE FAKE 99.984%| Senators Propose Giving States Option to Keep Affordable Care Act - The New York
  [Attempt 1/15] HTTP 400 Bad Request: {"error":"The expanded size of the tensor (515) must match the existing size (514) at non-singleton dimension 1.  Target
  Truncating further and retrying...
[30/72134] → Fake > FAKE FAKE 99.992%| Do You Belong To An Extraterrestrial Lineage? According to Sitchin’s interpretat
[31/72134] → Real > REAL REAL 99.997%| Zimbabwe's Mugabe appears in public for first time since coup Zimbabwe President
[32/72134] → Real > FAKE FAKE 99.997%| Credit Suisse Boss Faces Revolt From Bankers Over Strategy Shift - The New York
[33/72134] → Fake > FAKE FAKE 99.998%| THE ROBBING OF INNOCENCE: 12 Yr Old Students Given CDC Survey About Transgender,
[34/72134] → Real > REAL REAL 99.997%| Schaeuble to head German parliament, unblocking coalition talks Germany took a f
[35/72134] → Real > REAL REAL 99.997%| At U.S.-China summit, Trump presses Xi on trade, North Korea; progress cited Pre
[36/72134] → Real > REAL REAL 99.997%| Clinton extends lead over Trump to 7 points: Reuters/Ipsos Democratic presidenti
[37/72134] → Fake > FAKE FAKE 99.998%| JOE BIDEN’S SHOCKING ANNOUNCEMENT: “What the hell, man?” [Video] VP Joe Biden:
  [Attempt 1/15] HTTP 400 Bad Request: {"error":"The expanded size of the tensor (769) must match the existing size (514) at non-singleton dimension 1.  Target
  Truncating further and retrying...
  [Attempt 2/15] HTTP 400 Bad Request: {"error":"The expanded size of the tensor (678) must match the existing size (514) at non-singleton dimension 1.  Target
  Truncating further and retrying...
  [Attempt 3/15] HTTP 400 Bad Request: {"error":"The expanded size of the tensor (589) must match the existing size (514) at non-singleton dimension 1.  Target
  Truncating further and retrying...
[38/72134] → Fake > FAKE FAKE 99.808%| Comment une petite fille russe de 4 ans a appris à parler 7 langues langues , en
  [Attempt 1/15] HTTP 400 Bad Request: {"error":"The expanded size of the tensor (523) must match the existing size (514) at non-singleton dimension 1.  Target
  Truncating further and retrying...
[39/72134] → Fake > FAKE FAKE 99.997%| Emboldened NRA Threatens New York Times: ‘We’re Coming For You’ (VIDEO) The NRA
[40/72134] → Fake > FAKE FAKE 99.997%| Noam Chomsky GOES OFF On Donald Trump: ‘He’s A CLOWN!’ (VIDEO) renowned politica
[41/72134] → Fake > FAKE FAKE 99.998%| 5 Ways The Media Responded With Butthurt To Donald Trump’s Victory The media doe
[42/72134] → Real > FAKE FAKE 99.992%| Iran, Russia and Turkey Agree to Enforce Syria Cease-Fire, but Don’t Explain How
[43/72134] → Fake > FAKE FAKE 99.998%| BREAKING: OBAMA POISED To Exact Revenge On PUTIN With Unprecedented Cyber Attack
[44/72134] → Fake > FAKE FAKE 99.973%| True. Hillary needs a distraction and what better than a real "wag the dog" with
[45/72134] → Real > REAL REAL 99.996%| Trump says Brexit to be 'a great thing', wants quick trade deal with UK U.S. Pre
[46/72134] → Real > FAKE FAKE 99.994%| Sekulow: Expect ‘Whining Testimony’ from Comey ‘He Needs to ‘Grow up and Act Lik
[47/72134] → Real > REAL REAL 99.982%| Mayday on the Carolina Queen - The New York Times The seven fishermen aboard the
[48/72134] → Real > REAL REAL 99.997%| Illinois House passes $5 billion tax package, spending plan Illinois’ Democratic
[49/72134] → Fake > FAKE FAKE 99.858%| AT&T, Time Warner and the Death of Privacy AT&T, Time Warner and the Death of Pr
[50/72134] → Real > FAKE FAKE 99.991%| An Architect Who Built His Career on Resuscitating New York Landmarks - The New
  [Attempt 1/15] HTTP 400 Bad Request: {"error":"index out of range in self"}
  Truncating further and retrying...
[51/72134] → Fake > FAKE FAKE 99.951%| American dream, revisited by Pepe Escobar for the Strategic Culture Foundation

[52/72134] → Real > REAL REAL 99.995%| Fear of Iranian general left Iraqi Kurdish oil fields deserted When the Iraqi ar
[53/72134] → Real > FAKE FAKE 99.995%| In Once-Tolerant Mosul, a Social Unraveling That Feels Permanent - The New York
[54/72134] → Real > REAL REAL 99.996%| U.S. patent review board becomes conservative target In August, a dozen inventor
[55/72134] → Real > REAL REAL 99.997%| Trump interviews four for Fed chair job, to decide in two-three weeks U.S. Presi
[56/72134] → Real > FAKE FAKE 99.993%| Delingpole: Top Physicist and Leading Republicans Urge Trump to Quit Paris Clima
[57/72134] → Fake > REAL REAL 99.987%| Internationally-backed Libyan forces attack Daesh positions in Sirte Fighters lo
[58/72134] → Fake > FAKE FAKE 99.998%| OBAMACARE: Wheels Slowly Falling Off The Socialized Healthcare Train…Billions Wa
[59/72134] → Real > REAL REAL 99.996%| MSNBC, DNC reach deal to host Democratic debate in New Hampshire The tentative d
[60/72134] → Real > FAKE FAKE 99.990%| Georgetown Professors Instruct Students on How to ’Resist’ Trump Presidency - Br
[61/72134] → Real > REAL REAL 99.997%| U.S. House approves bill on financial regulation costs The U.S. House of Represe
[62/72134] → Fake > FAKE FAKE 99.998%| Ron Paul: ‘I Can’t Support Trump if He’s GOP Pick’ and ‘Neocons Will Love Hillar
[63/72134] → Fake > FAKE FAKE 99.995%| “PROGRESSIVE” DE BLASIO VISITS IOWA: Denies He’s Running For President…So He Jus
[64/72134] → Fake > FAKE FAKE 99.998%| Elijah Cummings Made Sure The GOP Is Well Aware They’re Hypocritical A**holes Re
[65/72134] → Fake > FAKE FAKE 99.990%| Will FBI Director Comey’s October Surprise Derail Hillary’s White House Bid? in:
[66/72134] → Fake > FAKE FAKE 99.946%| Man seems to think he helped out with World War Two Man seems to think he helped
[67/72134] → Fake > FAKE FAKE 99.998%| GOP Lawmaker To Trump: Stop Acting Like A ‘Fragile’ Snowflake Over Town Hall Pro
[68/72134] → Real > REAL REAL 99.997%| Trump extols corporate profits while seeking corporate tax cut U.S. President Do
  [Attempt 1/15] HTTP 400 Bad Request: {"error":"The expanded size of the tensor (528) must match the existing size (514) at non-singleton dimension 1.  Target
  Truncating further and retrying...
[69/72134] → Fake > FAKE FAKE 99.992%| Michael Moore Owes Me $4.99 28, 2016 | Reviews   Michael Moore in New York City'
[70/72134] → Real > REAL REAL 99.996%| Philippine ferry capsizes with 251 on board, four dead Four people were killed a
[71/72134] → Fake > FAKE FAKE 99.996%| HILLARY DNC SPEECH: “We Are Going To Follow The Money” [VIDEO]… WHILE GEORGE SOR
[72/72134] → Real > FAKE FAKE 99.990%| Donald Trump, Indonesia, Aleppo: Your Wednesday Evening Briefing - The New York
[73/72134] → Real > REAL REAL 99.996%| Death toll from blasts in Somalia's capital Mogadishu tops 200 More than 200 peo
[74/72134] → Real > FAKE FAKE 99.995%| Donald Trump Returns to Bashing ’Fake Media’ President Donald Trump returned to
  [Attempt 1/15] HTTP 400 Bad Request: {"error":"The expanded size of the tensor (527) must match the existing size (514) at non-singleton dimension 1.  Target
  Truncating further and retrying...
[75/72134] → Fake > FAKE FAKE 99.998%| Idiot Who Destroyed Trump Hollywood Star Gets EXACTLY What He Deserves Share Thi
  [Attempt 1/15] HTTP 400 Bad Request: {"error":"The expanded size of the tensor (554) must match the existing size (514) at non-singleton dimension 1.  Target
  Truncating further and retrying...
[76/72134] → Fake > FAKE FAKE 99.989%| Before The Great Flood 8 Kings Ruled Earth For 241,200 Years “…In 5 cities 8 kin
[77/72134] → Real > FAKE FAKE 99.989%| Three Arrested for Starting Massive Fire on Atlanta Interstate Bridge Three peop
[78/72134] → Fake > FAKE FAKE 99.998%| Collapsing: Why the ‘Russia Hack’ Witch Hunt Will Not End Well for Congress, or
[79/72134] → Real > REAL REAL 99.997%| White House voices concerns on Senate Sept. 11 lawsuit bill  The White House sai
[80/72134] → Fake > FAKE FAKE 99.998%| ‘Arab Spring’ and the Washington-Brussels-Riyadh Axis Be the First to Comment!
  [Attempt 1/15] HTTP 400 Bad Request: {"error":"The expanded size of the tensor (542) must match the existing size (514) at non-singleton dimension 1.  Target
  Truncating further and retrying...
[81/72134] → Real > REAL REAL 99.996%| Women knit pink 'pussyhats' for rally after Trump inauguration Editors Note: Att
[82/72134] → Fake > FAKE FAKE 99.975%| UNsilenced: Whistleblower Exposes UN Culture of Corruption up statistics in her
[83/72134] → Real > FAKE FAKE 99.993%| CNN Advertises Job Listing for Full Time ’Fake News’ Reporter CNN, the news orga
[84/72134] → Real > FAKE FAKE 99.993%| Snapchat Discover Takes a Hard Line on Misleading and Explicit Images - The New
[85/72134] → Fake > FAKE FAKE 99.995%| “IN YOUR FACE”: OBAMA LAUNCHES NEW #RefugeesWelcome Twitter Campaign On Twitter
[86/72134] → Real > REAL REAL 99.997%| U.S. allies show support for strikes on Syria U.S. allies expressed support on F
  [Attempt 1/15] HTTP 400 Bad Request: {"error":"The expanded size of the tensor (547) must match the existing size (514) at non-singleton dimension 1.  Target
  Truncating further and retrying...
[87/72134] → Fake > FAKE FAKE 99.998%| Homophobes Lose Their Damn Minds After Request To ‘Give Elsa A Girlfriend’ Hits
  [Attempt 1/15] HTTP 400 Bad Request: {"error":"The expanded size of the tensor (534) must match the existing size (514) at non-singleton dimension 1.  Target
  Truncating further and retrying...
[88/72134] → Real > REAL REAL 99.997%| Obama trolls Trump over 'mean tweet' on late night TV (This October 24 story has
[89/72134] → Fake > FAKE FAKE 99.998%| ANOTHER CLINTON CASUALTY? Sister Of Woman Who Allegedly Had Photos Proving Affai
[90/72134] → Real > REAL REAL 99.997%| Challenges to Trump's immigration orders spread to more U.S. states (In this Jan
[91/72134] → Real > REAL REAL 99.997%| Labour leader and other UK lawmakers could lose seats in cost cutting plan The l
  [Attempt 1/15] HTTP 400 Bad Request: {"error":"The expanded size of the tensor (518) must match the existing size (514) at non-singleton dimension 1.  Target
  Truncating further and retrying...
[92/72134] → Real > FAKE FAKE 99.991%| In a Corner of the Everglades, a Way of Life Ebbs - The New York Times EVERGLADE
[93/72134] → Real > REAL REAL 99.997%| Trump adviser: TPP 'dead,' will move quickly on bilateral trade deals President-
[94/72134] → Fake > FAKE FAKE 99.998%| Trevor Noah Compares Texans Excited About Open Carry Law To Gay Pride Parade Cel
[95/72134] → Fake > FAKE FAKE 99.998%| LOL! DEMOCRATS’ “Poster Child For Stupidity” Can’t Tell MSNBC Host What Her Part
[96/72134] → Fake > FAKE FAKE 99.998%| Trump THREATENS Comey Via Twitter In His Most Autocratic Move Yet Donald Trump h
[97/72134] → Real > REAL REAL 99.997%| Lithuania gets minority government as junior partner leaves Lithuania s governme
[98/72134] → Fake > FAKE FAKE 99.998%| Boiler Room EP #124 – Weather Warfare & CNN Goblin Pits Tune in to the Alternate
[99/72134] → Fake > FAKE FAKE 99.998%| COLLEGE REPUBLICANS PRESIDENT Attacked by Antifa : “Like a pack of wolves” left
[100/72134] → Fake > FAKE FAKE 99.994%| BEYONCE DOUBLES DOWN…Debuts #LEMONADE, Another Race Baiting, Cop-Hating, Pro-Oba
[101/72134] → Real > REAL REAL 99.997%| One person shot in Portland as anti-Trump protesters cross bridge: police One pe
[102/72134] → Real > FAKE FAKE 99.991%| For Helping Immigrants, Chobani’s Founder Draws Threats - The New York Times By
  [Attempt 1/15] HTTP 400 Bad Request: {"error":"The expanded size of the tensor (532) must match the existing size (514) at non-singleton dimension 1.  Target
  Truncating further and retrying...
[103/72134] → Fake > FAKE FAKE 99.997%| LOL! Costco Puts Hillary In “Milk Aisle” For Book Signing…Customers Shout “HILLA
[104/72134] → Fake > FAKE FAKE 99.998%| WATCH JUDGE ORDER PUNK WEARING “POLICE LIE” T-SHIRT TO LEAVE COURTROOM…Or Face C
[105/72134] → Fake > FAKE FAKE 99.983%| The World Sees a Diminished America The World Sees a Diminished America November
[106/72134] → Fake > FAKE FAKE 99.998%| CONSERVATIVE Has Message For “DREAMERS” Screaming “He’s not my President!” and I
[107/72134] → Fake > FAKE FAKE 99.998%| MARKETWATCH LEFTIST: MSM’s “Blatant” Anti Trump Bias May Be Suicidal
  [Attempt 1/15] HTTP 400 Bad Request: {"error":"The expanded size of the tensor (516) must match the existing size (514) at non-singleton dimension 1.  Target
  Truncating further and retrying...
[108/72134] → Fake > FAKE FAKE 99.997%| Comment on Facebook Daughter’s Day Hoax Is A Sign Of The Times by para kazanmak
[109/72134] → Fake > FAKE FAKE 99.998%| HATEFUL AND ANGRY OBAMA Tries To Bash Trump In Front Of Canadian Parliament…Real
[110/72134] → Real > REAL REAL 99.996%| DoD teams surveying US military sites for potential Gitmo transfers, lawmakers v
[111/72134] → Fake > FAKE FAKE 99.998%| On His Way Out The Door, Harry Reid Gives Big ‘F*ck You’ To Republicans And Hand
[112/72134] → Fake > FAKE FAKE 99.993%| BOMBSHELL: Justice Clarence Thomas Accused Of Sexual Misconduct (VIDEO) BOMBSHEL
[113/72134] → Real > FAKE FAKE 99.998%| German Police Kill Assailant After Ax Attack Aboard a Train - The New York Times
[114/72134] → Real > FAKE FAKE 63.905%| Austria Spearheads Balkan Frontier Defence Project Austria is joining forces wit
[115/72134] → Fake > FAKE FAKE 99.495%| CNN: One voter can make a difference by voting repeatedly Channel list
Followin
[116/72134] → Fake > FAKE FAKE 99.997%| Comment on 7 Effective Ways To Balance Hormones Naturally by Eat Your Way to Bal
[117/72134] → Fake > FAKE FAKE 99.998%| NATIVE AMERICAN TRIBE Will Offer Cash To Schools To STOP Using Indian Mascots…Wh
[118/72134] → Fake > FAKE FAKE 99.991%| This Poll Shows EXACTLY How Much Americans Detest Trump At this point in Trump s
[119/72134] → Fake > FAKE FAKE 99.998%| Unhinged NBA Coach: ‘White People Especially’ Need To Be Made ‘Uncomfortable’ [V
[120/72134] → Real > REAL REAL 99.996%| New York City budget boss to state: We're not a 'piggy bank' New York City’s fis
[121/72134] → Real > FAKE FAKE 99.993%| Why Long Voting Lines Could Have Long-Term Consequences - The New York Times In
[122/72134] → Real > FAKE FAKE 99.986%| Trump advisors try to pivot not fishtail **Want FOX News First in your inbox eve
[123/72134] → Fake > FAKE FAKE 99.995%| HILLARY WILL LAND IN PRISON, NOT THE OVAL OFFICE HILLARY WILL LAND IN PRISON, NO
[124/72134] → Real > REAL REAL 99.996%| Zimbabwe's Mugabe resigns, ending four decades of rule Robert Mugabe resigned as
[125/72134] → Real > FAKE FAKE 99.996%| Nuclear Option-The Speech: Trump Rendering Sullen Democrats Irrelevant - Breitba
[126/72134] → Real > FAKE FAKE 99.996%| Donald Trump Tax Records Show He Could Have Avoided Taxes for Nearly Two Decades
[127/72134] → Real > REAL REAL 99.996%| Factbox: Trump on Twitter (July 25) - Jeff Sessions, ObamaCare, trade deal The f
[128/72134] → Fake > FAKE FAKE 99.997%| HERE ARE THE FIVE State Department Rules That Hillary Violated [Video] While Hil
[129/72134] → Fake > FAKE FAKE 99.998%| DALLAS RALLY VIDEO: Trump Lets It Rip On The “Lame Stream” Media and Karl Rove T
[130/72134] → Real > REAL REAL 99.997%| California considers tighter lobbying rules as 2016 election nears California’s
[131/72134] → Fake > FAKE FAKE 99.987%| 5-STAR MOOCH, HER TAXPAYER FUNDED MOM And Meryl Streep Travel To Africa To Discu
[132/72134] → Fake > FAKE FAKE 99.993%| Homeschooling and Other Education Alternatives on the Rise Email
Horace Mann, t
[133/72134] → Real > REAL REAL 99.995%| Mexico presidential race roiled as leftist front-runner embraces right wing part
  [Attempt 1/15] HTTP 400 Bad Request: {"error":"The expanded size of the tensor (535) must match the existing size (514) at non-singleton dimension 1.  Target
  Truncating further and retrying...
[134/72134] → Real > FAKE FAKE 99.998%| The Atlantic VP: ’Democratization’ of News via the Internet Left People ’Overwhe
[135/72134] → Real > REAL REAL 99.996%| Kentucky county to appeal federal ruling striking right-to-work law Officials fo
[136/72134] → Fake > FAKE FAKE 99.991%| BREAKING: COURAGEOUS FEDERAL JUDGE DENIES OBAMA’S REQUEST TO LIFT STAY ON EXECUT

UnboundLocalError: local variable 'response' referenced before assignment

In [ ]:
df